# 1.Write the pandas program to change the order of index of a given series?

In [2]:
import pandas as pd
a = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(a)
a = a.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(a)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


# 2.Write a python program to add, subtract,multiple and divide two pandas series
sample series:[2,4,6,8,10],[1,3,5,7,9]

In [4]:
import pandas as pd
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])
s = s1 + s2
print("Add two Series:")
print(s)
print("Subtract two Series:")
s = s1 - s2
print(s)
print("Multiply two Series:")
s = s1 * s2
print(s)
print("Divide Series1 by Series2:")
s = s1 / s2
print(s)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


# 3.Write a python to convert a panda module series to python list and its type

In [6]:
import pandas as pd
s = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(s)
print(type(s))
print("Convert Pandas Series to Python list")
print(s.tolist())
print(type(s.tolist()))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


# 4. Write a panda program to select the rowa where the score is missing,i.e is NaN

In [8]:
import pandas as pd
import numpy as p
exam_data  = {'name': ['bindu', 'sukku', 'divya', 'madhu', 'shakeer', 'nani', 'chandu', 'sai', 'uday', 'manu'],
        'score': [12.5, 9, 16.5, p.nan, 9, 20, 14.5, p.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

f = pd.DataFrame(exam_data , index=labels)
print("Rows where score is missing:")
print(f[f['score'].isnull()])

Rows where score is missing:
    name  score  attempts qualify
d  madhu    NaN         3      no
h    sai    NaN         1      no


# 5.Write a numpy program to create a 3*3 matrix with values ranging from 2 to 10?

In [10]:
import numpy as p
x =  p.arange(2, 11).reshape(3,3)
print(x)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 6.IIIustrate the difference between ravel and flatten by taking considering multidimensinal array

In [15]:
a1=np.arange (2,11).reshape(3,3)
a2=np.arange(12,21).reshape(3,3)
print(a1.ravel())
print(a2.flatten())

[ 2  3  4  5  6  7  8  9 10]
[12 13 14 15 16 17 18 19 20]


## 7.Create a 3*3 numpy array,find out the minimum maximun  values and also their indices accordingly for each axes.Also find the statistical methods such as standard Deviation cumulative sum and product?

In [14]:
r=np.arange(2,11).reshape(3,3)
print(r)
print('min',r.min())
print('max',r.max())
print('std',r.std())
print('cumulative sum',r.cumsum())
print('cumlative product',r.cumprod())

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
min 2
max 10
std 2.581988897471611
cumulative sum [ 2  5  9 14 20 27 35 44 54]
cumlative product [      2       6      24     120     720    5040   40320  362880 3628800]


## 8.Create a data frame (with some values)find out information about that dataframe and description and sum of null values?

In [20]:
s=pd.DataFrame({"rollNo":[510,555,506,550,594],'sub1':[34,65,np.nan,34,76],'sub2':[65,34,45,56,np.nan]})
print(s)

   rollNo  sub1  sub2
0     510  34.0  65.0
1     555  65.0  34.0
2     506   NaN  45.0
3     550  34.0  56.0
4     594  76.0   NaN


## 9.Write a pandas program to get the first 3 rows and last 2 rows of a given data frame

In [17]:
s=pd.DataFrame(np.arange(2,27).reshape(5,5))
print(s)
print('first 3 rows')
print(s.head(3))
print('last 2 rows')
print(s.tail(2))

    0   1   2   3   4
0   2   3   4   5   6
1   7   8   9  10  11
2  12  13  14  15  16
3  17  18  19  20  21
4  22  23  24  25  26
first 3 rows
    0   1   2   3   4
0   2   3   4   5   6
1   7   8   9  10  11
2  12  13  14  15  16
last 2 rows
    0   1   2   3   4
3  17  18  19  20  21
4  22  23  24  25  26
